version: '3.6'

services:
  viz2:
    image: kris/ros_vis_img
    container_name: ros_visualizer_2
    build:
      context: .
      args:
        NVDRIVER: "460.91.03" # value of $(glxinfo | grep "OpenGL version string" | rev | cut -d" " -f1 | rev)
    networks:
      - ros
    extra_hosts:
      - "robotont-10:192.168.200.10"
#       - "robotont-10:172.17.206.199"
    environment:
      - "ROS_MASTER_URI=http://robotont-10:11311"
      - "ROS_HOSTNAME=ros_visualizer"
      - "DISPLAY=novnc:0.0"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
#    command: roslaunch turtle_tf2 turtle_tf2_sensor.launch
#    command: rviz
#    command: rosrun plotjuggler plotjuggler
    command: rqt
#    command: foxglove-studio
#    command: bash
    depends_on:
      - novnc
  novnc:
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - ros
networks:
  ros:
